### ISSUE TITLE
Can it read the .out file expoted from Hydrostar?

### ISSUE THREAD

**Issue by YangLeiTH** [BEMRosetta/BEMRosetta#18]
Dear @izabala123 

Hydrostar can also exported the wamit type output file, while it can not read the output file from hydrostar. Can it read the wamit type output file from hydrostar?

Best regards,

**Comment by izabala123** [comment]
Hi YangLeiTH

So far I have not had access to Hydrostar files, so reading them is not implemented in BEMRosetta.
Now BEMRosetta can read and write .out files from Wamit.
If you can give me some example files and their results, I can try to implement the reading of those files.

Best regards
Iñaki

**Comment by YangLeiTH** [comment]
Hi @izabala123 

- Hydrostar output file is similar to the wamit .out type, but it is a little different from the wamit type, so that it can not read Hydrostar output file. A typical Hydrostar output file is shown in the attachment. It shows the hydrodynamic coefficient of NREL OC3 spar.
[oc3spar.zip](https://github.com/BEMRosetta/BEMRosetta/files/10910294/oc3spar.zip)

**Comment by izabala123** [comment]
Hi YangLeiTH

Thank you for your examples. In some days I will try to include this.

Best regards
Iñaki

**Comment by YangLeiTH** [comment]
Hi @izabala123 

Thank you a lot.

Best regards,

**Comment by izabala123** [comment]
Hello YangLeiTH

I have been working with your file. It has some irregularities, like this
one:

 ************************************************************************

 2nd-order period = infinite                            Wavenumber = zero

 Period indices:     1212 Periods:   0.1676E+02  0.1676E+02
 ------------------------------------------------------------------------

The number 1212 should be 12 12. like in this one:

 ************************************************************************

 2nd-order period (sec) =   0.2513E+03     Wave frequency  0.0250

 Period indices:     12 14 Periods:   0.1676E+02  0.1571E+02
 ------------------------------------------------------------------------

It only happens when both indices are the same.

However this problem is harder:

 ************************************************************************

 2nd-order period (sec) =   0.7392E+01     Wave frequency  0.8500

 Period indices:     33 ** Periods:   0.6981E+01  0.3590E+01
 ------------------------------------------------------------------------

Now the index is a **.

I may try to find a way to overcome this. However I fear that the file has
more problems.
If you can solve the **, it would be great. However, if you tell me this is
the best you can get, I will do some changes to try to avoid this problem.

Best regards
Iñaki

**Comment by YangLeiTH** [comment]
Hi @izabala123 

I am sorry to hear that. This is the inherent output of Hydrostar, I reran hydrostar and got the same output with **. But I can ask hydrostar's official support what this ** means, and I will forward it to you when they reply. Thank you!

Best regards,
Lei Yang

**Comment by izabala123** [comment]
Hi Lei

The problem is that the field size seems to be 2, and ** means that it is overloaded. Maybe there is some formatting size option, or simply Hydrostar cannot process properly more than 100 frequencies in QTF.

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi Lei

I think I have been able to circumvent this problem, and others that I have found. In a few days I will upload a new version with the improvements.
Hydrostar format is 95% like Wamit, but this 5% is spread randomly...

Iñaki

**Comment by izabala123** [comment]
Hi Lei

New version is uploaded. Please check it in detail, I hope everything is loaded.

IÑaki

**Comment by YangLeiTH** [comment]
Hi IÑaki

Sorry for not replying for a long time, thank you very much, it helped me a lot, I asked the official staff of hydrostar, but they haven't replied yet, I will check the imported results carefully if there is any problem, I will reply to you if there is any problem, thank you very much!

Best regards,
Lei Yang

**Comment by YangLeiTH** [comment]
Hi IÑaki

Sorry for not replying for a long time, thank you very much, it helped me a lot, I asked the official staff of hydrostar, but they haven't replied yet, I will check the imported results carefully if there is any problem, I will reply to you if there is any problem, thank you very much!

Best regards,
Lei Yang

**Comment by izabala123** [comment]
Hi Yang Lei

Yes, this is because another different between Hydrostar and Wamit. 
I think that now it is solved.

Best regards
Iñaki

**Comment by YangLeiTH** [comment]
Hi @izabala123 

Thank you! I will try again later.

Best regards,

Yang Lei

**Comment by izabala123** [comment]
Hi @YangLeiTH 

In reviewing more Hydrostar cases, I believe that in addition to the .out it is necessary to have the .mcn file. 
Can you confirm if the .out file is normally saved in the same folder as the .mcn file? 
I'm seeing that the .out always includes the XBODY and COG in 0,0,0, even if it's not true. Also, some parameters like REFPOINT_BODY and REFWAVE are critical, as the .out does not follow all Wamit rules.

Best regards
Iñaki
