### ISSUE TITLE
Center of Gravity 

### ISSUE THREAD

**Issue by riasatmorshed** [BEMRosetta/BEMRosetta#47]
My question is more of a theoretical one, as in, how BEMRosetta handles the center of gravity. I have drafted my rectangle (1.2m x 0.2m and 0.7 m) in way that the whole 1.2m x 0.2m x 0.7m are below the (0,0,0).

Now the geometric center of gravity of the body should be at (0,0,-0.35m), as it is a uniform rectangular body, right? But in BEMRosetta summary, it is showing the center of gravity to be at (0,0,0), even though the center of buoyancy is shown to be at (0,0, -0.35m). 
![CG_CB](https://github.com/BEMRosetta/BEMRosetta/assets/104738257/7b88c0b4-b157-48fa-95e7-5bba672b638a)
![hydrostatic_Stiffness_BEMRosetta](https://github.com/BEMRosetta/BEMRosetta/assets/104738257/bd210a50-40f8-4103-8053-46f829ace88e)
![mesh_dot_gdf](https://github.com/BEMRosetta/BEMRosetta/assets/104738257/a2842dba-f8a5-4e97-8cc3-a33e014e3e16)

I am attaching some screenshots from my BEMRosetta GUI. Let me know if you need anything else. Thanks in advance!

**Comment by izabala123** [comment]
Hi Md Riasat

The gdf format does not include the centre of gravity. Therefore, BEMRosetta does not know where it is, and defaults to 0,0,0. As you have entered the mesh, the centre of buoyancy is calculated. You can easily modify the centre of gravity and mass, and see how that affects the stiffness matrix. Simply enter them as shown in the image, clicking in each case on the attached button to update them. You can see that you can also change the body axes, if you want the centre of application of the moments due to the hydrostatic stiffness not to coincide with the CG.

![image](https://github.com/BEMRosetta/BEMRosetta/assets/38589221/3d1613de-798e-42f2-bde7-35e21bbde2b7)

Best regards
Iñaki

**Comment by riasatmorshed** [comment]
Many thanks, @izabala123!

**Comment by riasatmorshed** [comment]
Many thanks, @izabala123!

**Comment by izabala123** [comment]
I am pleased 😄
