### ISSUE TITLE
Crashes on loading hydrodynamic data in Windows 10

### ISSUE THREAD

**Issue by pn-206** [BEMRosetta/BEMRosetta#9]
Hi!

Firstly, thank you for working on this amazing tool, it's helped me a lot.

I've been able to load meshes, manipulate and save them and have used the BEM Solver to produce the relevant files to run NEMOH which I've done successfully.

However, when I try to load the hydrodynamic data by opening the Nemoh.cal file, BEMRosetta abruptly closes after starting the process.  I initially thought it might be something to do with my Nemoh output files but the same behaviour is observed even if I try and load up the hydrodynamic data that's packaged with the distribution (BEMRosetta\examples\nemoh\ellipsoid\Nemoh.cal).

I'm running BEMRosetta by simply executing the .exe file in the bin folder.  I'm running the latest version of Windows 10 and I've pulled the latest version of the repo.

I hope you can help.

Many thanks
Prash

**Comment by izabala123** [comment]
Hi Prash

Thank you for your nice words.

I have just downloaded the binary and loaded BEMRosetta\examples\nemoh\ellipsoid\Nemoh.cal.
Please confirm me if this is what you try to do.
Here I enclose you the screenshot I get:

![image](https://user-images.githubusercontent.com/38589221/153728752-eeb5f1a2-b046-46fe-b718-97a9d7c6a8fa.png)

Best regards
Iñaki

**Comment by tvanenckevort** [comment]
Hi,

Thanks a lot for the development of this tool, it helps me out tremendously!

Unfortunately I am having a similar problem to Prash. I am also running BEMRosetta on windows 10 by just running the .exe file as suggested. Whenever I try to open a Nemoh.cal file of my mesh into the 'Hydrodynamic Coefficients' tab of BEMRosetta it crashes immediately. See the screenshot of what I want to do, it crashes after I click 'open'. I want to do this in order to easily check the coefficients of my mesh. Is am wondering if there is any way to fix this, or that maybe there is another way to quickly view the coefficients of my mesh?

Thanks a lot in advance!

With kind regards,
Tijmen

![BEMRosetta](https://user-images.githubusercontent.com/79256082/171200027-eaa87a30-a4c0-495d-b595-33f6daf88fa2.jpg)

**Comment by izabala123** [comment]
The fix is uploaded. Please check it. Sorry for the inconveniences.
